name: NBA Oracle Live Sync

on:
  push:
    branches: [ main ] # This triggers the robot every time you save code

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Sync Files to Azure
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az storage blob upload-batch --connection-string "${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}" --destination '$web' --source . --overwrite
